/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.signup;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author TEST
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
        addphs(tickno);
        addphs(rcno1);

    }

    public void addphs(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }

    public void removephs(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        plot = new javax.swing.JTextField();
        rcno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        atime = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        tickno = new javax.swing.JTextField();
        rcno1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }

            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("EXIT VEHICLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 0, 102, 38));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RCNO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Plot No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Full name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        name.setEditable(false);
        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 155, -1));

        plot.setEditable(false);
        plot.setBackground(new java.awt.Color(255, 255, 255));
        plot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(plot, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 155, -1));

        rcno.setEditable(false);
        rcno.setBackground(new java.awt.Color(255, 255, 255));
        rcno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(rcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 155, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Arrival Time");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 130, -1));

        atime.setEditable(false);
        atime.setBackground(new java.awt.Color(255, 255, 255));
        atime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(atime, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 155, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Generate Reciept");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 420, 314));

        print.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 430, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Plot Name ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 110, -1));

        pname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 155, -1));

        tickno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tickno.setText("Search by Ticke No");
        tickno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ticknoFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                ticknoFocusLost(evt);
            }
        });
        getContentPane().add(tickno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        rcno1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rcno1.setText("Search by RC_NO");
        rcno1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rcno1FocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                rcno1FocusLost(evt);
            }
        });
        getContentPane().add(rcno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 150, -1));

        jLabel8.setText("OR");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 47, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parking.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/DBMS", "root", "Shivam@123");
            // String ticknum=tickno.getText();
            // if("Search by Ticke No".equals(ticknum))
            // ticknum="11";
            // int id;
            // id = Integer.parseInt(ticknum);
            // String rc_no1=rcno1.getText();

            String ticknum = tickno.getText().trim();
            String rc_no1 = rcno1.getText().trim();

            int id = -1;

            try {
                id = Integer.parseInt(ticknum);
            } catch (Exception ex) {
                // Search is being done by RC number
            }
            Statement stm = con.createStatement();
            // String sql = "SELECT `rc_no`,`full_name`,`plot`,`atime`,`plot_name` FROM
            // `vehicle_details` where ticket_no='"+id+"' or rc_no='"+rc_no1+"'";
            String sql = "SELECT `ticket_no`,`rc_no`,`full_name`,`plot`,`atime`,`plot_name` FROM `vehicle_details` where ticket_no='"
                    + id + "' or rc_no='" + rc_no1 + "'";

            ResultSet rs = stm.executeQuery(sql);
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Sorry Record Not Found");
                rcno.setText("");
                name.setText("");
                plot.setText("");
                atime.setText("");
                pname.setText("");

            } else {
                tickno.setText(rs.getString("ticket_no"));
                rcno.setText(rs.getString("rc_no"));
                name.setText(rs.getString("full_name"));
                plot.setText(rs.getString("plot"));
                atime.setText(rs.getString("atime"));
                pname.setText(rs.getString("plot_name"));

            }

            con.close();
        } catch (Exception e) {
            System.out.print("ERROR OCCURED" + e);
        } // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/DBMS", "root", "Shivam@123");
            // String ticknum=tickno.getText();
            // int id;
            // id = Integer.parseInt(ticknum);
            // String rc_no=rcno1.getText();
            // PreparedStatement pst1=con.prepareStatement("delete from vehicle_details
            // where ticket_no=? or rc_no=?");
            // pst1.setInt(1,id);
            // pst1.setString(2,rc_no);

            // pst1.execute();

            String rc_no = rcno.getText();

            PreparedStatement pst1 = con.prepareStatement(
                    "delete from vehicle_details where rc_no=?");

            pst1.setString(1, rc_no);

            pst1.executeUpdate();

            // Statement stm2=con.createStatement();
            ResultSet rs;
            String pnm = pname.getText();
            PreparedStatement pst3 = con.prepareStatement("SELECT total_space FROM `park_space` where space_name=?");
            pst3.setString(1, pnm);
            rs = pst3.executeQuery();
            // String sql2 = "SELECT total_space FROM `park_space` where
            // ticket_no='"+pnm+"'";

            // ResultSet rs2 =stm2.executeQuery(sql2);
            // if(rs2.next()==true)
            // {
            while (rs.next()) {
                String t_s = rs.getString("total_space");
                int t_ss = Integer.parseInt(t_s);
                int t_sss = t_ss + 1;
                System.out.println(t_sss);
                PreparedStatement pst2 = con
                        .prepareStatement("update park_space set total_space='" + t_sss + "' where space_name=?");
                pst2.setString(1, pnm);
                pst2.execute();
                System.out.print("updated");

                PreparedStatement pst5 = con.prepareStatement("update all_vehicle set rate='" + 40 + "' where rc_no=?");
                pst5.setString(1, rc_no);
                pst5.execute();

                Date obj = new Date();
                String date = obj.toString();
                PreparedStatement pst6 = con
                        .prepareStatement("update all_vehicle set dtime='" + date + "' where rc_no=?");
                pst6.setString(1, rc_no);
                pst6.execute();
                // }
            }
        }
        // catch(Exception e){}

        catch (Exception e) {
            e.printStackTrace();
        }

        area.setText("*************************************************************\n");
        area.setText(area.getText() + "*                               PARKING TICKET                      *\n");
        area.setText(area.getText() + "**************************************************************");
        Date obj = new Date();
        String date = obj.toString();
        area.setText(area.getText() + "\n\nDriver Name=" + name.getText() + "\n");
        area.setText(area.getText() + "----------------------------------------\n");
        area.setText(area.getText() + "Vehicle RC NO=" + rcno.getText() + "\n");
        area.setText(area.getText() + "----------------------------------------\n");
        area.setText(area.getText() + "Plot NO=" + plot.getText() + "\n");
        area.setText(area.getText() + "----------------------------------------\n");
        area.setText(area.getText() + "Arrival Time=" + atime.getText() + "\n");
        area.setText(area.getText() + "----------------------------------------\n");
        area.setText(area.getText() + "Dispature Time=" + date + "\n");
        area.setText(area.getText() + "----------------------------------------\n");
        area.setText(area.getText() + "Amount =" + 40 + "\n");
        area.setText(area.getText() + "----------------------------------------\n");

        // TODO add your handling code here:
    }// GEN-LAST:event_jButton2ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_printActionPerformed
        try {
            area.print(); // TODO add your handling code here:

        } catch (Exception e) {

        }
    }// GEN-LAST:event_printActionPerformed

    private void ticknoFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_ticknoFocusGained
        if (tickno.getText().equals("Search by Ticke No")) {
            tickno.setText(null);
            tickno.requestFocus();
            removephs(tickno);
        }
    }// GEN-LAST:event_ticknoFocusGained

    private void rcno1FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_rcno1FocusGained
        if (rcno1.getText().equals("Search by RC_NO")) {
            rcno1.setText(null);
            rcno1.requestFocus();
            removephs(rcno1);
        } // TODO add your handling code here:
    }// GEN-LAST:event_rcno1FocusGained

    private void rcno1FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_rcno1FocusLost
        if (rcno1.getText().length() == 0) {
            addphs(rcno1);
            rcno1.setText("Search by RC_NO");
        } // TODO add your handling code here:
    }// GEN-LAST:event_rcno1FocusLost

    private void ticknoFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_ticknoFocusLost
        if (tickno.getText().length() == 0) {
            addphs(tickno);
            tickno.setText("Search by Ticke No");
        } // TODO add your handling code here:
    }// GEN-LAST:event_ticknoFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow(); // TODO add your handling code here:
    }// GEN-LAST:event_formWindowGainedFocus

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        home hvp = new home();
        hvp.show(); // TODO add your handling code here:
    }// GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JTextField atime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField plot;
    private javax.swing.JTextField pname;
    private javax.swing.JButton print;
    private javax.swing.JTextField rcno;
    private javax.swing.JTextField rcno1;
    private javax.swing.JTextField tickno;
    // End of variables declaration//GEN-END:variables
}
